name: polyline_2
description: Polyline encoding algorithm for encoding and decoding a list of coordinates
version: 1.0.0
homepage: https://github.com/TNorbury/polyline.dart-2
repository: https://github.com/TNorbury/polyline.dart-2
issue_tracker: https://github.com/TNorbury/polyline.dart-2

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
